#!/bin/sh
# MIT License, Wannes Meert, 2020

if [ -z "$1" ]; then
	# No file given, open and activate Texpad
	open -a Texpad.app
	# osascript <<EOF
# tell application "Texpad"
  # activate
# end tell
# EOF
else
	FP="$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"
	# echo "$FP"
	# open -a Texpad.app $1
	# Use AppleScript to tell Texpad to open the given file
	osascript <<EOF
set filePath to "$FP"
set fileAlias to POSIX file filePath as alias
tell application "Texpad"
  activate
  open alias fileAlias
end tell
EOF
fi

